# docker-compose for development of ubersystem
x-uber: &uber
  build: .
  environment: 
    - DB_CONNECTION_STRING=postgresql://uber_db:uber_db@db:5432/uber_db
    - sideboard_cherrypy_server.socket_port=80
    - sideboard_cherrypy_server.socket_host=0.0.0.0
    - sideboard_cherrypy_server.socket_timeout=1
    - sideboard_cherrypy_tools.sessions.host=redis
    - sideboard_cherrypy_tools.sessions.prefix=uber
    - sideboard_cherrypy_tools.sessions.storage_type=redis
    - sideboard_loggers_cherrypy.access=DEBUG
    - uber_redis_host=redis
    - uber_secret_broker_url=amqp://celery:celery@rabbitmq:5672/uber
  volumes:
    - $PWD:/app/plugins/uber

services: 
  web:
    <<: *uber
    ports:
      - 80:80
  celery-beat:
    <<: *uber
    command: ['celery-beat']
  celery-worker:
    <<: *uber
    command: ['celery-worker']
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=uber_db
      - POSTGRES_USER=uber_db
      - POSTGRES_DB=uber_db
  redis:
    image: redis
  rabbitmq:
    ports:
      - "5672"
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=celery
      - RABBITMQ_DEFAULT_PASS=celery
      - RABBITMQ_DEFAULT_VHOST=uber