---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-uploads
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.web.storage.capacity }}"