---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-beats
  labels:
    app: celery-beats
spec:
  replicas: {{ .Values.beats.replicas }}
  selector:
    matchLabels:
      app: celery-beats
  template:
    metadata:
      labels:
        app: celery-beats
    spec:
      volumes:
      - name: web-uploads
        persistentVolumeClaim:
          claimName: web-uploads
      terminationGracePeriodSeconds: 5
      {{- template "uber.initContainers" .}}
      containers:
      - name: celery-beats
        image: "{{ .Values.beats.image.repository }}:{{ .Values.beats.image.tag }}"
        args: ["celery-beat"]
        env:
        {{- template "uber.environment" . }}
        volumeMounts:
        - mountPath: "/app/plugins/uber/uploaded_files"
          name: web-uploads

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      volumes:
      - name: web-uploads
        persistentVolumeClaim:
          claimName: web-uploads
      terminationGracePeriodSeconds: 5
      {{- template "uber.initContainers" .}}
      containers:
      - name: celery-worker
        image: "{{ .Values.workers.image.repository }}:{{ .Values.workers.image.tag }}"
        args: ["celery-worker"]
        env:
        {{- template "uber.environment" . }}
        volumeMounts:
        - mountPath: "/app/plugins/uber/uploaded_files"
          name: web-uploads